### ISSUE TITLE
[task] Flamelink Website Enhancements

### ISSUE THREAD

**Issue by gitdubz** [flamelink/flamelink-website#180]
- [x] Ordering on the Case Study overview page is not working (https://www.gatsbyjs.com/docs/graphql-reference/) Have a look at the sort option. We need to sort by order

~~- [ ] Add Flamelink feature icons and text like on the features page to showcase the features used by the project~~

~~- [ ] Add section for tech used (example web, ios, android, node, etc)~~

- [x] SEO section - I think it’s vital to have an SEO section on the case studies (see landing page SEO and duplicate for case studies)

- [x] Add option in feature section to set content to full width (if only content - content full width, if only text, text full width)

**Comment by Flamelink-support** [comment]
Jason tested and it is working.
